(function(factory) {

  define([], factory);

})(function() {

  var contants = {
    'PLAY_APPOINTED_TRACK': 'PLAY_APPOINTED_TRACK',
    'TOGGLE_LOOP_MODE': 'TOGGLE_LOOP_MODE',
    'TOGGLE_SHUFFLE_MODE': 'TOGGLE_SHUFFLE_MODE',

    'AUDIO_UPDATE_CURRENT_TIME': 'AUDIO_UPDATE_CURRENT_TIME',
    'AUDIO_CHANGE_CURRENT_TIME': 'AUDIO_CHANGE_CURRENT_TIME',
    'AUDIO_CHANGE_VOLUME': 'AUDIO_CHANGE_VOLUME',
    'AUDIO_TOGGLE_MUTE': 'AUDIO_TOGGLE_MUTE',
    'AUDIO_ENDED': 'AUDIO_ENDED',
    'AUDIO_PLAYING': 'AUDIO_PLAYING',
    'AUDIO_PAUSE': 'AUDIO_PAUSE'
  }

  return contants;

});